export { default as QMINDCard } from "./QMINDCardImg.png";
export { default as MemoriaCard } from "./MemoriaCardImg.png";
export { default as UMGCard } from "./UMGCardImg.png";
export { default as uCard } from "./ustudiosCardImg.png";
export { default as veryCard } from "./vcsCardImg.png";
export { default as boldCard } from "./boldCardImg.png";
export { default as HeroImage } from "./hero-image.png";
export { default as CUCAICard } from "./CUCAICardImg.png";
export { default as RecalcCard } from "./RecalcCardImg.png";
